angular.module('crudAppLocacao.controllers', 
		['ClienteControllers',
		 'FuncionarioControllers',
		 'CategoriaControllers',
		 'LocacaoControllers',
		 'MultaControllers',
		 'VeiculoControllers',
		 'AvariaControllers'
		 ]
);
